'use strict';
const fs=require('node:fs'), assert=require('node:assert/strict');
const root=fs.readFileSync('index.html','utf8');
const app=fs.readFileSync('web/index.html','utf8');
assert.match(root,/<base\s+href="\.\/web\/"/);
assert.match(root,/<script\s+defer\s+src="\.\/app\.js"/);
assert.match(root,/<link\s+rel="stylesheet"\s+href="\.\/styles\.css"/);
assert.match(root,/<link\s+rel="manifest"\s+href="\.\/manifest\.webmanifest"/);
assert(!root.includes('http-equiv="refresh"') && !root.includes('location.replace('),'Root site must render app, not redirect');
for(const id of ['timer-display','todo-items','ringtone-banner']) assert(root.includes(`id="${id}"`),`Missing ${id} at root`);
for(const asset of ['app.js','styles.css','manifest.webmanifest','sw.js','icon.svg']) assert(fs.existsSync('web/'+asset));
assert(app.includes('<title>MASUM CHRONOS'), 'Direct /web app missing');
assert(!fs.existsSync('.github/workflows/pages.yml'), 'Conflicting Pages Actions publisher must be absent');
console.log('PAGES: root app, /web/ asset paths and manifest, no redirect, single branch publisher: PASS');
